services:
  app:
    container_name: pg_enum_benchmarks_app
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - internal-net
    command: "php -v"

  db:
    container_name: pg_enum_benchmarks_db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - internal-net

networks:
  internal-net:
    name: pg_enum_benchmarks_net
    driver: bridge

