services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: php:8.4-alpine
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - internal-net

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    networks:
      - internal-net

networks:
  internal-net:
    name: ${COMPOSE_PROJECT_NAME}-internal-net
    driver: bridge

